name: Fullstack CI

on:
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: codebase/rdicidr-0.1.0

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 15.x
        cache: 'npm'
        cache-dependency-path: codebase/rdicidr-0.1.0/package-lock.json
    - run: npm ci
      name: Install dependencies
    - run: npm run lint
  
  test:
    runs-on: ubuntu-latest
    needs: lint

    defaults:
      run:
        working-directory: codebase/rdicidr-0.1.0

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 15.x
        cache: 'npm'
        cache-dependency-path: codebase/rdicidr-0.1.0/package-lock.json
    - run: npm ci
      name: Install dependencies
    - run: CI=true npm run test
  
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    defaults:
      run:
        working-directory: codebase/rdicidr-0.1.0

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 15.x
        cache: 'npm'
        cache-dependency-path: codebase/rdicidr-0.1.0/package-lock.json
    - run: npm ci
      name: Install dependencies
    - run: npm run build
